apiVersion: apps/v1
kind: Deployment
metadata:
  name: flush-old-versions
  labels:
    app: flush-old-versions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flush-old-versions
  template:
    metadata:
      labels:
        app: flush-old-versions
    spec:
      containers:
      - name: flush-old-versions
        image: gcr.io/mechmania2017/flush-old-versions:latest
        ports:
        - containerPort: 3000
        env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: creds
                key: mongo
          - name: RABBITMQ_URI
            valueFrom:
              secretKeyRef:
                name: creds
                key: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: flush-old-versions-service
spec:
  type: LoadBalancer
  selector:
    app: flush-old-versions
  ports:
  - port: 80
    name: flush-old-versions-service
    targetPort: 3000
    protocol: TCP